version: '3.3'

services:
  ratings_web:
    container_name: ratings_web
    build: .
    restart: always
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    ports:
      - 5000:5000
      - 3002:3000
    depends_on:
      - ratings_db
  ratings_db:
    container_name: ratings_db
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3307:3306
    expose:
      - 3306
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: